name: Commitlint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install --save-dev @commitlint/{cli,config-conventional}
      - run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.cjs
      - run: npx commitlint --from=HEAD~1 --to=HEAD
