name: lint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm i -g markdownlint-cli@0.41.0
      - run: markdownlint --config .markdownlint.json --ignore-path .markdownlintignore "**/*.md"

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install yamllint==1.35.1
      - run: yamllint -c .yamllint .

  pre_commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pre-commit
      - run: pre-commit run --all-files
