name: yamllint

on:
  pull_request:
  workflow_dispatch:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install yamllint==1.35.1
      - run: yamllint -c .yamllint .
